/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.lkapitman;

import com.github.lkapitman.commands.ExampleCommand;
import com.github.lkapitman.listener.ExampleListener;
import com.github.lkapitman.listener.JoinListener;

import org.bukkit.plugin.java.JavaPlugin;

public class App extends JavaPlugin {

    @Override
    public void onEnable() {
        this.getCommand("example").setExecutor(new ExampleCommand());
        getServer().getPluginManager().registerEvents(new ExampleListener(), this);
        getServer().getPluginManager().registerEvents(new JoinListener(), this);
    }
    
}
